In [1]:
import pandas as pd
path_airbnb = "/Users/miriamg/Documents/Mid-Term-Project_ML_Ironhack/Mid-term project/airbnb_DF.csv"
mx_airbnb = pd.read_csv(path_airbnb)
mx_airbnb

id                                               name    host_id  \
0         35797                                        Villa Dante     153786   
1         44616                                  CONDESA HAUS  B&B     196253   
2         56074               Great space in historical San Rafael     265650   
3         58955                 Entire beautiful duplex in la Roma     282620   
4         61792  Spacious Clean Quiet room (own bath) in la Con...     299558   
...         ...                                                ...        ...   
19847  47216226                  De Lux Apartment Loft Polanco 402  377262235   
19848  47216443      Loft pequeño con cocineta a pasos de  Reforma   87544364   
19849  47218209               Loft Deluxe Departamento Polanco 408  377262235   
19850  47219108         Stuning apartment in Santa Fe 4beds/3baths  377662942   
19851  47219520  Habitación a unos pasos de Bosques de Chapultepec  127885823   

                                host_name  neighbourhood_group  \
0                                    Dici                  NaN   
1      Condesa Haus Bed & Breakfast  CDMX                  NaN   
2                                   Maris                  NaN   
3                                   Laura                  NaN   
4                                 Roberto                  NaN   
...                                   ...                  ...   
19847                            Rosa Ma.                  NaN   
19848                             Antonio                  NaN   
19849                            Rosa Ma.                  NaN   
19850                               Susan                  NaN   
19851                                Sara                  NaN   

               neighbourhood   latitude  longitude        room_type  price  \
0      Cuajimalpa de Morelos  19.383990 -99.273350  Entire home/apt   4019   
1                 Cuauhtémoc  19.410060 -99.176450  Entire home/apt   8286   
2                 Cuauhtémoc  19.437780 -99.155490  Entire home/apt    650   
3                 Cuauhtémoc  19.422920 -99.157750  Entire home/apt   1447   
4                 Cuauhtémoc  19.412590 -99.179590     Private room   1206   
...                      ...        ...        ...              ...    ...   
19847         Miguel Hidalgo  19.431680 -99.182640  Entire home/apt   1061   
19848             Cuauhtémoc  19.433830 -99.153780  Entire home/apt    426   
19849         Miguel Hidalgo  19.431540 -99.183100  Entire home/apt   1059   
19850  Cuajimalpa de Morelos  19.360834 -99.269901  Entire home/apt   1760   
19851         Miguel Hidalgo  19.434000 -99.208420     Private room    186   

       minimum_nights  number_of_reviews last_review  reviews_per_month  \
0                   1                  0         NaN                NaN   
1                   1                 49  2020-10-25               0.44   
2                   4                 60  2019-07-24               1.59   
3                  15                 42  2020-01-31               0.38   
4                   2                 52  2019-11-03               1.36   
...               ...                ...         ...                ...   
19847               2                  0         NaN                NaN   
19848               1                  0         NaN                NaN   
19849               1                  0         NaN                NaN   
19850               2                  0         NaN                NaN   
19851               3                  0         NaN                NaN   

       calculated_host_listings_count  availability_365  
0                                   1               364  
1                                  10               364  
2                                   2                 0  
3                                   1                 0  
4                                   2                 0  
...                               ...               ...  
198

In [2]:
#Getting info from the dataset

import pandas as pd
path_airbnb = "/Users/miriamg/Documents/Mid-Term-Project_ML_Ironhack/Mid-term project/airbnb_DF.csv"
mx_airbnb = pd.read_csv(path_airbnb)

mx_airbnb.columns #The most important columns are: 'neighbourhood',  'room_type', 'price',
       #'minimum_nights','number_of_reviews','calculated_host_listings_count'

    
unique_values = mx_airbnb.nunique()
print("Number of unique values in each column:")
print(unique_values) #calculated_host_listings count means the amount of ads that the host has on the platform, or professionalism


#for column in mx_airbnb.columns:
    #unique_values = mx_airbnb[column].unique()
    #print(f"Unique values in {column}: {unique_values}")
    
mx_airbnb = mx_airbnb[['neighbourhood','room_type', 'price',
       'minimum_nights', 'number_of_reviews','calculated_host_listings_count',
       'availability_365']]

mx_airbnb 

Number of unique values in each column:
id                                19852
name                              19159
host_id                           11412
host_name                          3718
neighbourhood_group                   0
neighbourhood                        16
latitude                          10626
longitude                          9093
room_type                             4
price                              2185
minimum_nights                       65
number_of_reviews                   316
last_review                        1278
reviews_per_month                   766
calculated_host_listings_count       41
availability_365                    363
dtype: int64


neighbourhood        room_type  price  minimum_nights  \
0      Cuajimalpa de Morelos  Entire home/apt   4019               1   
1                 Cuauhtémoc  Entire home/apt   8286               1   
2                 Cuauhtémoc  Entire home/apt    650               4   
3                 Cuauhtémoc  Entire home/apt   1447              15   
4                 Cuauhtémoc     Private room   1206               2   
...                      ...              ...    ...             ...   
19847         Miguel Hidalgo  Entire home/apt   1061               2   
19848             Cuauhtémoc  Entire home/apt    426               1   
19849         Miguel Hidalgo  Entire home/apt   1059               1   
19850  Cuajimalpa de Morelos  Entire home/apt   1760               2   
19851         Miguel Hidalgo     Private room    186               3   

       number_of_reviews  calculated_host_listings_count  availability_365  
0                      0                               1               364  
1                     49                              10               364  
2                     60                               2                 0  
3                     42                               1                 0  
4                     52                               2                 0  
...                  ...                             ...               ...  
19847                  0                               3               365  
19848                  0                               9               365  
19849                  0                               3               365  
19850                  0                               1               365  
19851                  0                               9               365  

[19852 rows x 7 columns]

In [3]:
#Checking how clean the data is:

def data_frame_overview(data_frame):
    print(f'Column names: \n {data_frame.columns}\n')
    print(f'Dimensions: {data_frame.shape}\n')
    print(data_frame.info())
    print(f'nan values: \n {data_frame.isna().sum()}\n')
    print(f'nan values: \n {data_frame.isnull().sum()}\n')
    return data_frame.head(50)

def null_check(data_frame):
    print(f'Total null values per row: \n{data_frame.isnull().sum(axis=1)}\n')
    print(f'Total null values per column: \n{data_frame.isnull().sum()}\n')
    
def dropna_rows_cols(data_frame, row_thresh, col_thresh):
    '''
    removes rows and columns with null values

    parameters:
    data_frame: data_frame from which to remove rows and columns
    row_thresh: minimum threshold for the number of non-null values that a row must have in order to be kept
    col_thresh: minimum threshold for the number of non-null values that a column must have in order to be kept

    returns:
    data frame in which the rows and columns containing null values have been removed
    '''
    rows_before = len(data_frame)
    cols_before = len(data_frame.columns)
    data_frame.dropna(thresh = row_thresh, inplace = True)
    data_frame.dropna(axis=1, thresh = col_thresh, inplace = True)
    rows_after = len(data_frame)
    cols_after = len(data_frame.columns)
    rows_deleted = rows_before - rows_after
    cols_deleted = cols_before - cols_after
    print(f'Deleted {rows_deleted} rows')
    print(f'Deleted {cols_deleted} columns')

    return data_frame
    
data_frame_overview(mx_airbnb) #drop host_name and id, could be interesting to analyze if some hosts, of make inferences on the location with tatitude longitude, but maybe for other project
null_check(mx_airbnb)

Column names: 
 Index(['neighbourhood', 'room_type', 'price', 'minimum_nights',
       'number_of_reviews', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

Dimensions: (19852, 7)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19852 entries, 0 to 19851
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   neighbourhood                   19852 non-null  object
 1   room_type                       19852 non-null  object
 2   price                           19852 non-null  int64 
 3   minimum_nights                  19852 non-null  int64 
 4   number_of_reviews               19852 non-null  int64 
 5   calculated_host_listings_count  19852 non-null  int64 
 6   availability_365                19852 non-null  int64 
dtypes: int64(5), object(2)
memory usage: 1.1+ MB
None
nan values: 
 neighbourhood                     0
room_type                     

In [4]:
mx_airbnb
# Assuming the hosts want to rent the whole year we consider days rented= 365-(availability_365)
# Assuming all the host have been there at least for a year

neighbourhood        room_type  price  minimum_nights  \
0      Cuajimalpa de Morelos  Entire home/apt   4019               1   
1                 Cuauhtémoc  Entire home/apt   8286               1   
2                 Cuauhtémoc  Entire home/apt    650               4   
3                 Cuauhtémoc  Entire home/apt   1447              15   
4                 Cuauhtémoc     Private room   1206               2   
...                      ...              ...    ...             ...   
19847         Miguel Hidalgo  Entire home/apt   1061               2   
19848             Cuauhtémoc  Entire home/apt    426               1   
19849         Miguel Hidalgo  Entire home/apt   1059               1   
19850  Cuajimalpa de Morelos  Entire home/apt   1760               2   
19851         Miguel Hidalgo     Private room    186               3   

       number_of_reviews  calculated_host_listings_count  availability_365  
0                      0                               1               364  
1                     49                              10               364  
2                     60                               2                 0  
3                     42                               1                 0  
4                     52                               2                 0  
...                  ...                             ...               ...  
19847                  0                               3               365  
19848                  0                               9               365  
19849                  0                               3               365  
19850                  0                               1               365  
19851                  0                               9               365  

[19852 rows x 7 columns]

In [5]:
#Adding column of days rented

mx_airbnb['days_rented'] = [365 - a for a in mx_airbnb['availability_365']]
mx_airbnb

neighbourhood        room_type  price  minimum_nights  \
0      Cuajimalpa de Morelos  Entire home/apt   4019               1   
1                 Cuauhtémoc  Entire home/apt   8286               1   
2                 Cuauhtémoc  Entire home/apt    650               4   
3                 Cuauhtémoc  Entire home/apt   1447              15   
4                 Cuauhtémoc     Private room   1206               2   
...                      ...              ...    ...             ...   
19847         Miguel Hidalgo  Entire home/apt   1061               2   
19848             Cuauhtémoc  Entire home/apt    426               1   
19849         Miguel Hidalgo  Entire home/apt   1059               1   
19850  Cuajimalpa de Morelos  Entire home/apt   1760               2   
19851         Miguel Hidalgo     Private room    186               3   

       number_of_reviews  calculated_host_listings_count  availability_365  \
0                      0                               1               364   
1                     49                              10               364   
2                     60                               2                 0   
3                     42                               1                 0   
4                     52                               2                 0   
...                  ...                             ...               ...   
19847                  0                               3               365   
19848                  0                               9               365   
19849                  0                               3               365   
19850                  0                               1               365   
19851                  0                               9               365   

       days_rented  
0                1  
1                1  
2              365  
3              365  
4              365  
...            ...  
19847            0  
19848            0  
19849            0  
19850            0  
19851            0  

[19852 rows x 8 columns]

In [6]:
#Adding column of revenue which is our target variable

mx_airbnb['revenue'] = mx_airbnb['days_rented']* mx_airbnb['price']
mx_airbnb.drop(columns=['availability_365'], inplace= True)
mx_airbnb

neighbourhood        room_type  price  minimum_nights  \
0      Cuajimalpa de Morelos  Entire home/apt   4019               1   
1                 Cuauhtémoc  Entire home/apt   8286               1   
2                 Cuauhtémoc  Entire home/apt    650               4   
3                 Cuauhtémoc  Entire home/apt   1447              15   
4                 Cuauhtémoc     Private room   1206               2   
...                      ...              ...    ...             ...   
19847         Miguel Hidalgo  Entire home/apt   1061               2   
19848             Cuauhtémoc  Entire home/apt    426               1   
19849         Miguel Hidalgo  Entire home/apt   1059               1   
19850  Cuajimalpa de Morelos  Entire home/apt   1760               2   
19851         Miguel Hidalgo     Private room    186               3   

       number_of_reviews  calculated_host_listings_count  days_rented  revenue  
0                      0                               1            1     4019  
1                     49                              10            1     8286  
2                     60                               2          365   237250  
3                     42                               1          365   528155  
4                     52                               2          365   440190  
...                  ...                             ...          ...      ...  
19847                  0                               3            0        0  
19848                  0                               9            0        0  
19849                  0                               3            0        0  
19850                  0                               1            0        0  
19851                  0                               9            0        0  

[19852 rows x 8 columns]

In [7]:
categorical_df = mx_airbnb.select_dtypes(include = 'object')
categorical_df.nunique()

#Both categorical values are nominal


neighbourhood    16
room_type         4
dtype: int64

In [8]:
for column in categorical_df.columns:
    unique_values = mx_airbnb[column].unique()
    print(f"Unique values in {column}: {unique_values}")

Unique values in neighbourhood: ['Cuajimalpa de Morelos' 'Cuauhtémoc' 'Coyoacán' 'Miguel Hidalgo'
 'Benito Juárez' 'Azcapotzalco' 'Iztacalco' 'Tlalpan'
 'La Magdalena Contreras' 'Venustiano Carranza' 'Álvaro Obregón'
 'Gustavo A. Madero' 'Xochimilco' 'Iztapalapa' 'Tláhuac' 'Milpa Alta']
Unique values in room_type: ['Entire home/apt' 'Private room' 'Hotel room' 'Shared room']


In [9]:
categorical_nominals_df = pd.get_dummies(categorical_df, dtype= int)

categorical_nominals_df

neighbourhood_Azcapotzalco  neighbourhood_Benito Juárez  \
0                               0                            0   
1                               0                            0   
2                               0                            0   
3                               0                            0   
4                               0                            0   
...                           ...                          ...   
19847                           0                            0   
19848                           0                            0   
19849                           0                            0   
19850                           0                            0   
19851                           0                            0   

       neighbourhood_Coyoacán  neighbourhood_Cuajimalpa de Morelos  \
0                           0                                    1   
1                           0                                    0   
2                           0                                    0   
3                           0                                    0   
4                           0                                    0   
...                       ...                                  ...   
19847                       0                                    0   
19848                       0                                    0   
19849                       0                                    0   
19850                       0                                    1   
19851                       0                                    0   

       neighbourhood_Cuauhtémoc  neighbourhood_Gustavo A. Madero  \
0                             0                                0   
1                             1                                0   
2                             1                                0   
3                             1                                0   
4                             1                                0   
...                         ...                              ...   
19847                         0                                0   
19848                         1                                0   
19849                         0                                0   
19850                         0                                0   
19851                         0                                0   

       neighbourhood_Iztacalco  neighbourhood_Iztapalapa  \
0                            0                         0   
1                            0                         0   
2                            0                         0   
3                            0                         0   
4                            0                         0   
...                        ...                       ...   
19847                        0                         0   
19848                        0                         0   
19849                        0                         0   
19850                        0                         0   
19851                        0                         0   

       neighbourhood_La Magdalena Contreras  neighbourhood_Miguel Hidalgo  \
0                                         0                             0   
1                                         0                             0   
2                                         0                             0   
3                                         0                             0   
4                                         0                             0   
...                                     ...                           ...   
19847                                     0                             1   
19848                                     0                             0   
19849                                     0                             1   
19850                                     0                      

In [10]:
numerical_df = mx_airbnb.select_dtypes(include ='number')
numerical_df

price  minimum_nights  number_of_reviews  \
0       4019               1                  0   
1       8286               1                 49   
2        650               4                 60   
3       1447              15                 42   
4       1206               2                 52   
...      ...             ...                ...   
19847   1061               2                  0   
19848    426               1                  0   
19849   1059               1                  0   
19850   1760               2                  0   
19851    186               3                  0   

       calculated_host_listings_count  days_rented  revenue  
0                                   1            1     4019  
1                                  10            1     8286  
2                                   2          365   237250  
3                                   1          365   528155  
4                                   2          365   440190  
...                               ...          ...      ...  
19847                               3            0        0  
19848                               9            0        0  
19849                               3            0        0  
19850                               1            0        0  
19851                               9            0        0  

[19852 rows x 6 columns]

In [11]:
complete_df = pd.concat([categorical_nominals_df, numerical_df],axis=1)

complete_df

neighbourhood_Azcapotzalco  neighbourhood_Benito Juárez  \
0                               0                            0   
1                               0                            0   
2                               0                            0   
3                               0                            0   
4                               0                            0   
...                           ...                          ...   
19847                           0                            0   
19848                           0                            0   
19849                           0                            0   
19850                           0                            0   
19851                           0                            0   

       neighbourhood_Coyoacán  neighbourhood_Cuajimalpa de Morelos  \
0                           0                                    1   
1                           0                                    0   
2                           0                                    0   
3                           0                                    0   
4                           0                                    0   
...                       ...                                  ...   
19847                       0                                    0   
19848                       0                                    0   
19849                       0                                    0   
19850                       0                                    1   
19851                       0                                    0   

       neighbourhood_Cuauhtémoc  neighbourhood_Gustavo A. Madero  \
0                             0                                0   
1                             1                                0   
2                             1                                0   
3                             1                                0   
4                             1                                0   
...                         ...                              ...   
19847                         0                                0   
19848                         1                                0   
19849                         0                                0   
19850                         0                                0   
19851                         0                                0   

       neighbourhood_Iztacalco  neighbourhood_Iztapalapa  \
0                            0                         0   
1                            0                         0   
2                            0                         0   
3                            0                         0   
4                            0                         0   
...                        ...                       ...   
19847                        0                         0   
19848                        0                         0   
19849                        0                         0   
19850                        0                         0   
19851                        0                         0   

       neighbourhood_La Magdalena Contreras  neighbourhood_Miguel Hidalgo  \
0                                         0                             0   
1                                         0                             0   
2                                         0                             0   
3                                         0                             0   
4                                         0                             0   
...                                     ...                           ...   
19847                                     0                             1   
19848                                     0                             0   
19849                                     0                             1   
19850                                     0                      

## X-y split

In [12]:
X = complete_df.drop(columns=['revenue'])
y = complete_df[['revenue']]


In [13]:
y

revenue
0         4019
1         8286
2       237250
3       528155
4       440190
...        ...
19847        0
19848        0
19849        0
19850        0
19851        0

[19852 rows x 1 columns]

## Train-test split

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, random_state=42)

In [16]:
y_test

revenue
1901    250408
9512    128400
5140    799398
8660    129500
438     248600
...        ...
15610   124200
9835         0
9526     30940
2359    341224
673     252070

[4963 rows x 1 columns]

## Standardize the data. PowerTransformer

In [17]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, PowerTransformer

In [18]:
scaler = PowerTransformer()

In [19]:
scaler_fitted = scaler.fit(X_train)
X_train= scaler_fitted.transform(X_train)
X_train

array([[-0.11459854, -0.42710351,  3.26766691, ..., -1.26862563,
         0.37236447,  1.19852853],
       [-0.11459854, -0.42710351, -0.30602874, ..., -1.26862563,
         0.37236447, -1.3763439 ],
       [-0.11459854, -0.42710351, -0.30602874, ...,  0.54153472,
        -1.01033696,  1.01276632],
       ...,
       [-0.11459854, -0.42710351, -0.30602874, ..., -1.26862563,
        -1.01033696,  0.76307521],
       [-0.11459854, -0.42710351, -0.30602874, ...,  1.20059915,
        -1.01033696, -0.45451154],
       [-0.11459854, -0.42710351, -0.30602874, ..., -1.26862563,
        -1.01033696,  0.95620547]])

In [20]:
X_test = scaler_fitted.transform(X_test)
X_test

array([[-0.11459854, -0.42710351, -0.30602874, ..., -1.26862563,
        -1.01033696,  1.01276632],
       [-0.11459854, -0.42710351, -0.30602874, ...,  0.50248629,
        -0.10229216,  0.84686668],
       [-0.11459854, -0.42710351, -0.30602874, ...,  0.75239421,
         0.66656293,  0.98867083],
       ...,
       [-0.11459854, -0.42710351, -0.30602874, ...,  0.6431487 ,
         1.34686813, -0.50529618],
       [-0.11459854, -0.42710351, -0.30602874, ...,  0.84131067,
         1.28729236, -0.43095741],
       [-0.11459854,  2.3413528 , -0.30602874, ...,  0.09129175,
        -1.01033696,  1.01276632]])

In [21]:
scaler_fitted_y= scaler.fit(y_train)
y_train= scaler_fitted_y.transform(y_train)
y_train

array([[ 1.49138907],
       [-1.60070689],
       [ 1.04224256],
       ...,
       [ 0.20205362],
       [-0.08723799],
       [ 0.36119397]])

In [22]:
y_test = scaler_fitted_y.transform(y_test)
y_test

array([[0.97227486],
       [0.6754088 ],
       [1.56758246],
       ...,
       [0.13700923],
       [1.12062067],
       [0.97537201]])

## Applying linear regression

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
lm = LinearRegression()
model = lm.fit(X_train, y_train)

In [25]:
model.coef_

array([[-4.60513505e+10, -1.47059133e+11, -1.13923183e+11,
        -6.22817702e+10, -1.97668986e+11, -5.50121808e+10,
        -4.70984242e+10, -5.02088455e+10, -3.71467797e+10,
        -1.49350431e+11, -1.41471997e+10, -8.20178026e+10,
        -1.94330036e+10, -6.10777453e+10, -3.40686380e+10,
        -8.90438899e+10,  4.19754218e+09,  9.45612571e+08,
         4.17644987e+09,  1.17684182e+09,  2.51296997e-01,
         7.52449036e-03,  3.75366211e-02, -2.33459473e-03,
         9.28314209e-01]])

In [26]:
model.intercept_

array([-5.1147208e-06])

## Predict the yearly income

In [27]:
#I want to understand why if I don't convert to dataframes the model goes crazy
#Not sure I'm really using the transformed dataframe

#X_train= pd.DataFrame(X_train)
#X_test= pd.DataFrame(X_test)
#y_test= pd.DataFrame(y_test)
#y_train= pd.DataFrame(y_train)

#X_train #when transforming I lose the names of the columns, why?

In [28]:
#random_host = X_test.sample()

In [29]:
#random_host

In [30]:
#model.predict(random_host)

In [31]:
#Inverse transform
#pt.inverse_transform(model.predict(random_host))

## Create predictions for the test set

In [32]:
y_pred = model.predict(X_test)

In [33]:
y_pred= pd.DataFrame(y_pred)

In [34]:
y_test = pd.DataFrame(y_test)

In [35]:
y_test = y_test.reset_index(drop = True)

In [36]:
residuals_df = pd.concat([y_test, y_pred], axis=1)
residuals_df.columns = ["y_test", "y_pred"]
residuals_df

y_test    y_pred
0     0.972275  0.980517
1     0.675409  0.772976
2     1.567582  1.371313
3     0.679009  0.673467
4     0.968886  1.053387
...        ...       ...
4958  0.661419  0.759444
4959 -1.600707 -1.721700
4960  0.137009 -0.103090
4961  1.120621  0.507524
4962  0.975372  1.048260

[4963 rows x 2 columns]

In [37]:
residuals_df["residual"] = residuals_df["y_test"]- residuals_df["y_pred"]

In [38]:
residuals_df.head()

y_test    y_pred  residual
0  0.972275  0.980517 -0.008242
1  0.675409  0.772976 -0.097568
2  1.567582  1.371313  0.196270
3  0.679009  0.673467  0.005542
4  0.968886  1.053387 -0.084501

## Calculating metrics

In [39]:
mean_error = residuals_df["residual"].mean()
mean_error

-0.001026759724527051

In [40]:
from sklearn.metrics import mean_squared_error as mse, mean_absolute_error as mae

In [41]:
mse(y_test, y_pred)

0.07068341242971102

In [42]:
mae(y_test, y_pred)

0.20355478605166724

In [43]:
rmse= mse( y_test, y_pred, squared = False)
rmse

0.26586352218706316

## Computing R2_score for test_set

In [44]:
from sklearn.metrics import r2_score

In [45]:
r2_score(y_test, y_pred)

0.9298621943703257

## Computing R2_score for train_set

In [46]:
y_pred_train = pd.DataFrame(model.predict(X_train))

In [47]:
round(r2_score(y_train, y_pred_train),2)

0.93

In [48]:
X_train

array([[-0.11459854, -0.42710351,  3.26766691, ..., -1.26862563,
         0.37236447,  1.19852853],
       [-0.11459854, -0.42710351, -0.30602874, ..., -1.26862563,
         0.37236447, -1.3763439 ],
       [-0.11459854, -0.42710351, -0.30602874, ...,  0.54153472,
        -1.01033696,  1.01276632],
       ...,
       [-0.11459854, -0.42710351, -0.30602874, ..., -1.26862563,
        -1.01033696,  0.76307521],
       [-0.11459854, -0.42710351, -0.30602874, ...,  1.20059915,
        -1.01033696, -0.45451154],
       [-0.11459854, -0.42710351, -0.30602874, ..., -1.26862563,
        -1.01033696,  0.95620547]])

## Feature importance plot

In [49]:
feature_names = list(X_train.columns) #Why the names of the columns are transformed into numbers?
feature_names

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [ ]:
coefficients = model.coef_
coefficients = [i for i in coefficients[0]]

fi = {"name": feature_names, "coeff": coefficients}
fi_df = pd.DataFrame(fi)

fi_df

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

fi_df = fi_df.sort_values(by='coeff', ascending=False)
plt.figure(figsize=(10,12))

sns.barplot(y= fi_df['name'], x = fi_df['coeff'])